using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buddies.API.Migrations
{
    public partial class AddLocations : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Locations",
                columns: table => new
                {
                    LocationID = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Address = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Locations", x => x.LocationID);
                });

            migrationBuilder.InsertData(
                table: "Locations",
                columns: new[] { "LocationID", "Address" },
                values: new object[,]
                {
                    { 1, "Toronto, Ontario" },
                    { 2, "Montreal, Quebec" },
                    { 3, "Vancouver, British Columbia" },
                    { 4, "Calgary, Alberta" },
                    { 5, "Edmonton, Alberta" },
                    { 6, "Ottawa, Ontario" },
                    { 7, "Mississauga, Ontario" },
                    { 8, "Winnipeg, Manitoba" },
                    { 9, "Quebec City, Quebec" },
                    { 10, "Hamilton, Ontario" },
                    { 11, "Brampton, Ontario" },
                    { 12, "Surrey, British Columbia" },
                    { 13, "Kitchener, Ontario" },
                    { 14, "Laval, Quebec" },
                    { 15, "Halifax, Nova Scotia" },
                    { 16, "London, Ontario" },
                    { 17, "Victoria, British Columbia" },
                    { 18, "Markham, Ontario" },
                    { 19, "St. Catharines, Ontario" },
                    { 20, "Niagara Falls, Ontario" },
                    { 21, "Vaughan, Ontario" },
                    { 22, "Gatineau, Quebec" },
                    { 23, "Windsor, Ontario" },
                    { 24, "Saskatoon, Saskatchewan" },
                    { 25, "Longueuil, Quebec" },
                    { 26, "Burnaby, British Columbia" },
                    { 27, "Regina, Saskatchewan" },
                    { 28, "Richmond, British Columbia" },
                    { 29, "Richmond Hill, Ontario" },
                    { 30, "Oakville, Ontario" },
                    { 31, "Burlington, Ontario" },
                    { 32, "Barrie, Ontario" },
                    { 33, "Oshawa, Ontario" },
                    { 34, "Sherbrooke, Quebec" },
                    { 35, "Saguenay, Quebec" },
                    { 36, "Levis, Quebec" },
                    { 37, "Kelowna, British Columbia" },
                    { 38, "Abbotsford, British Columbia" },
                    { 39, "Coquitlam, British Columbia" },
                    { 40, "Trois-Rivieres, Quebec" },
                    { 41, "Guelph, Ontario" },
                    { 42, "Cambridge, Ontario" },
                    { 43, "Whitby, Ontario" },
                    { 44, "Ajax, Ontario" },
                    { 45, "Langley, British Columbia" },
                    { 46, "Saanich, British Columbia" },
                    { 47, "Terrebonne, Quebec" },
                    { 48, "Milton, Ontario" },
                    { 49, "St. John's, Newfoundland and Labrador" },
                    { 50, "Moncton, New Brunswick" },
                    { 51, "Thunder Bay, Ontario" },
                    { 52, "Dieppe, New Brunswick" },
                    { 53, "Waterloo, Ontario" },
                    { 54, "Delta, British Columbia" },
                    { 55, "Chatham, Ontario" },
                    { 56, "Red Deer, Alberta" },
                    { 57, "Kamloops, British Columbia" },
                    { 58, "Brantford, Ontario" },
                    { 59, "Cape Breton, Nova Scotia" },
                    { 60, "Lethbridge, Alberta" },
                    { 61, "Saint-Jean-sur-Richelieu, Quebec" },
                    { 62, "Clarington, Ontario" },
                    { 63, "Pickering, Ontario" },
                    { 64, "Nanaimo, British Columbia" },
                    { 65, "Sudbury, Ontario" },
                    { 66, "North Vancouver, British Columbia" },
                    { 67, "Brossard, Quebec" },
                    { 68, "Repentigny, Quebec" },
                    { 69, "Newmarket, Ontario" },
                    { 70, "Chilliwack, British Columbia" },
                    { 71, "White Rock, British Columbia" },
                    { 72, "Maple Ridge, British Columbia" },
                    { 73, "Peterborough, Ontario" },
                    { 74, "Kawartha Lakes, Ontario" },
                    { 75, "Prince George, British Columbia" },
                    { 76, "Sault Ste. Marie, Ontario" },
                    { 77, "Sarnia, Ontario" },
                    { 78, "Wood Buffalo, Alberta" },
                    { 79, "New Westminster, British Columbia" },
                    { 80, "Chateauguay, Quebec" },
                    { 81, "Saint-Jerome, Quebec" },
                    { 82, "Drummondville, Quebec" },
                    { 83, "Saint John, New Brunswick" },
                    { 84, "Caledon, Ontario" },
                    { 85, "St. Albert, Alberta" },
                    { 86, "Granby, Quebec" },
                    { 87, "Medicine Hat, Alberta" },
                    { 88, "Grande Prairie, Alberta" },
                    { 89, "St. Thomas, Ontario" },
                    { 90, "Airdrie, Alberta" },
                    { 91, "Halton Hills, Ontario" },
                    { 92, "Saint-Hyacinthe, Quebec" },
                    { 93, "Lac-Brome, Quebec" },
                    { 94, "Port Coquitlam, British Columbia" },
                    { 95, "Fredericton, New Brunswick" },
                    { 96, "Blainville, Quebec" },
                    { 97, "Aurora, Ontario" },
                    { 98, "Welland, Ontario" },
                    { 99, "North Bay, Ontario" },
                    { 100, "Beloeil, Quebec" },
                    { 101, "Belleville, Ontario" },
                    { 102, "Mirabel, Quebec" },
                    { 103, "Shawinigan, Quebec" },
                    { 104, "Dollard-des-Ormeaux, Quebec" },
                    { 105, "Brandon, Manitoba" },
                    { 106, "Rimouski, Quebec" },
                    { 107, "Cornwall, Ontario" },
                    { 108, "Stouffville, Ontario" },
                    { 109, "Georgina, Ontario" },
                    { 110, "Victoriaville, Quebec" },
                    { 111, "Vernon, British Columbia" },
                    { 112, "Duncan, British Columbia" },
                    { 113, "Saint-Eustache, Quebec" },
                    { 114, "Quinte West, Ontario" },
                    { 115, "Charlottetown, Prince Edward Island" },
                    { 116, "Mascouche, Quebec" },
                    { 117, "West Vancouver, British Columbia" },
                    { 118, "Salaberry-de-Valleyfield, Quebec" },
                    { 119, "Rouyn-Noranda, Quebec" },
                    { 120, "Timmins, Ontario" },
                    { 121, "Sorel-Tracy, Quebec" },
                    { 122, "New Tecumseth, Ontario" },
                    { 123, "Woodstock, Ontario" },
                    { 124, "Boucherville, Quebec" },
                    { 125, "Mission, British Columbia" },
                    { 126, "Vaudreuil-Dorion, Quebec" },
                    { 127, "Brant, Ontario" },
                    { 128, "Lakeshore, Ontario" },
                    { 129, "Innisfil, Ontario" },
                    { 130, "Prince Albert, Saskatchewan" },
                    { 131, "Langford Station, British Columbia" },
                    { 132, "Bradford West Gwillimbury, Ontario" },
                    { 133, "Campbell River, British Columbia" },
                    { 134, "Spruce Grove, Alberta" },
                    { 135, "Moose Jaw, Saskatchewan" },
                    { 136, "Penticton, British Columbia" },
                    { 137, "Port Moody, British Columbia" },
                    { 138, "Leamington, Ontario" },
                    { 139, "East Kelowna, British Columbia" },
                    { 140, "Cote-Saint-Luc, Quebec" },
                    { 141, "Val-d'Or, Quebec" },
                    { 142, "Owen Sound, Ontario" },
                    { 143, "Stratford, Ontario" },
                    { 144, "Lloydminster, Saskatchewan" },
                    { 145, "Pointe-Claire, Quebec" },
                    { 146, "Orillia, Ontario" },
                    { 147, "Alma, Quebec" },
                    { 148, "Orangeville, Ontario" },
                    { 149, "Fort Erie, Ontario" },
                    { 150, "LaSalle, Ontario" },
                    { 151, "Sainte-Julie, Quebec" },
                    { 152, "Leduc, Alberta" },
                    { 153, "North Cowichan, British Columbia" },
                    { 154, "Chambly, Quebec" },
                    { 155, "Okotoks, Alberta" },
                    { 156, "Sept-Iles, Quebec" },
                    { 157, "Centre Wellington, Ontario" },
                    { 158, "Saint-Constant, Quebec" },
                    { 159, "Grimsby, Ontario" },
                    { 160, "Boisbriand, Quebec" },
                    { 161, "Conception Bay South, Newfoundland and Labrador" },
                    { 162, "Saint-Bruno-de-Montarville, Quebec" },
                    { 163, "Sainte-Therese, Quebec" },
                    { 164, "Cochrane, Alberta" },
                    { 165, "Thetford Mines, Quebec" },
                    { 166, "Courtenay, British Columbia" },
                    { 167, "Magog, Quebec" },
                    { 168, "Whitehorse, Yukon" },
                    { 169, "Woolwich, Ontario" },
                    { 170, "Clarence-Rockland, Ontario" },
                    { 171, "Fort Saskatchewan, Alberta" },
                    { 172, "East Gwillimbury, Ontario" },
                    { 173, "Lincoln, Ontario" },
                    { 174, "La Prairie, Quebec" },
                    { 175, "Tecumseh, Ontario" },
                    { 176, "Mount Pearl Park, Newfoundland and Labrador" },
                    { 177, "Amherstburg, Ontario" },
                    { 178, "Saint-Lambert, Quebec" },
                    { 179, "Brockville, Ontario" },
                    { 180, "Collingwood, Ontario" },
                    { 181, "Scugog, Ontario" },
                    { 182, "Kingsville, Ontario" },
                    { 183, "Baie-Comeau, Quebec" },
                    { 184, "Paradise, Newfoundland and Labrador" },
                    { 185, "Uxbridge, Ontario" },
                    { 186, "Essa, Ontario" },
                    { 187, "Candiac, Quebec" },
                    { 188, "Oro-Medonte, Ontario" },
                    { 189, "Varennes, Quebec" },
                    { 190, "Strathroy-Caradoc, Ontario" },
                    { 191, "Wasaga Beach, Ontario" },
                    { 192, "New Glasgow, Nova Scotia" },
                    { 193, "Wilmot, Ontario" },
                    { 194, "Essex, Ontario" },
                    { 195, "Fort St. John, British Columbia" },
                    { 196, "Kirkland, Quebec" },
                    { 197, "L'Assomption, Quebec" },
                    { 198, "Westmount, Quebec" },
                    { 199, "Saint-Lazare, Quebec" },
                    { 200, "Chestermere, Alberta" },
                    { 201, "Huntsville, Ontario" },
                    { 202, "Corner Brook, Newfoundland and Labrador" },
                    { 203, "Riverview, New Brunswick" },
                    { 204, "Lloydminster, Alberta" },
                    { 205, "Joliette, Quebec" },
                    { 206, "Yellowknife, Northwest Territories" },
                    { 207, "Squamish, British Columbia" },
                    { 208, "Mont-Royal, Quebec" },
                    { 209, "Riviere-du-Loup, Quebec" },
                    { 210, "Cobourg, Ontario" },
                    { 211, "Cranbrook, British Columbia" },
                    { 212, "Beaconsfield, Quebec" },
                    { 213, "Springwater, Ontario" },
                    { 214, "Dorval, Quebec" },
                    { 215, "Thorold, Ontario" },
                    { 216, "Camrose, Alberta" },
                    { 217, "South Frontenac, Ontario" },
                    { 218, "Pitt Meadows, British Columbia" },
                    { 219, "Port Colborne, Ontario" },
                    { 220, "Quispamsis, New Brunswick" },
                    { 221, "Mont-Saint-Hilaire, Quebec" },
                    { 222, "Bathurst, New Brunswick" },
                    { 223, "Saint-Augustin-de-Desmaures, Quebec" },
                    { 224, "Oak Bay, British Columbia" },
                    { 225, "Sainte-Marthe-sur-le-Lac, Quebec" },
                    { 226, "Salmon Arm, British Columbia" },
                    { 227, "Port Alberni, British Columbia" },
                    { 228, "Esquimalt, British Columbia" },
                    { 229, "Deux-Montagnes, Quebec" },
                    { 230, "Miramichi, New Brunswick" },
                    { 231, "Niagara-on-the-Lake, Ontario" },
                    { 232, "Saint-Lin--Laurentides, Quebec" },
                    { 233, "Beaumont, Alberta" },
                    { 234, "Middlesex Centre, Ontario" },
                    { 235, "Inverness, Nova Scotia" },
                    { 236, "Stony Plain, Alberta" },
                    { 237, "Petawawa, Ontario" },
                    { 238, "Pelham, Ontario" },
                    { 239, "Selwyn, Ontario" },
                    { 240, "Loyalist, Ontario" },
                    { 241, "Midland, Ontario" },
                    { 242, "Colwood, British Columbia" },
                    { 243, "Central Saanich, British Columbia" },
                    { 244, "Sainte-Catherine, Quebec" },
                    { 245, "Port Hope, Ontario" },
                    { 246, "L'Ancienne-Lorette, Quebec" },
                    { 247, "Saint-Basile-le-Grand, Quebec" },
                    { 248, "Swift Current, Saskatchewan" },
                    { 249, "Edmundston, New Brunswick" },
                    { 250, "Russell, Ontario" },
                    { 251, "North Grenville, Ontario" },
                    { 252, "Yorkton, Saskatchewan" },
                    { 253, "Tracadie, New Brunswick" },
                    { 254, "Bracebridge, Ontario" },
                    { 255, "Greater Napanee, Ontario" },
                    { 256, "Tillsonburg, Ontario" },
                    { 257, "Steinbach, Manitoba" },
                    { 258, "Hanover, Manitoba" },
                    { 259, "Terrace, British Columbia" },
                    { 260, "Springfield, Manitoba" },
                    { 261, "Gaspe, Quebec" },
                    { 262, "Kenora, Ontario" },
                    { 263, "Cold Lake, Alberta" },
                    { 264, "Summerside, Prince Edward Island" },
                    { 265, "Comox, British Columbia" },
                    { 266, "Sylvan Lake, Alberta" },
                    { 267, "Pincourt, Quebec" },
                    { 268, "West Lincoln, Ontario" },
                    { 269, "Matane, Quebec" },
                    { 270, "Brooks, Alberta" },
                    { 271, "Sainte-Anne-des-Plaines, Quebec" },
                    { 272, "West Nipissing / Nipissing Ouest, Ontario" },
                    { 273, "Rosemere, Quebec" },
                    { 274, "Mistassini, Quebec" },
                    { 275, "Grand Falls, Newfoundland and Labrador" },
                    { 276, "Clearview, Ontario" },
                    { 277, "St. Clair, Ontario" },
                    { 278, "Canmore, Alberta" },
                    { 279, "North Battleford, Saskatchewan" },
                    { 280, "Pembroke, Ontario" },
                    { 281, "Mont-Laurier, Quebec" },
                    { 282, "Strathmore, Alberta" },
                    { 283, "Saugeen Shores, Ontario" },
                    { 284, "Thompson, Manitoba" },
                    { 285, "Lavaltrie, Quebec" },
                    { 286, "High River, Alberta" },
                    { 287, "Severn, Ontario" },
                    { 288, "Sainte-Sophie, Quebec" },
                    { 289, "Saint-Charles-Borromee, Quebec" },
                    { 290, "Portage La Prairie, Manitoba" },
                    { 291, "Thames Centre, Ontario" },
                    { 292, "Mississippi Mills, Ontario" },
                    { 293, "Powell River, British Columbia" },
                    { 294, "South Glengarry, Ontario" },
                    { 295, "North Perth, Ontario" },
                    { 296, "Mercier, Quebec" },
                    { 297, "South Stormont, Ontario" },
                    { 298, "Saint-Colomban, Quebec" },
                    { 299, "Lacombe, Alberta" },
                    { 300, "Sooke, British Columbia" },
                    { 301, "Dawson Creek, British Columbia" },
                    { 302, "Lake Country, British Columbia" },
                    { 303, "Trent Hills, Ontario" },
                    { 304, "Sainte-Marie, Quebec" },
                    { 305, "Guelph/Eramosa, Ontario" },
                    { 306, "Truro, Nova Scotia" },
                    { 307, "Amos, Quebec" },
                    { 308, "The Nation / La Nation, Ontario" },
                    { 309, "Ingersoll, Ontario" },
                    { 310, "Winkler, Manitoba" },
                    { 311, "Wetaskiwin, Alberta" },
                    { 312, "Central Elgin, Ontario" },
                    { 313, "Lachute, Quebec" },
                    { 314, "West Grey, Ontario" },
                    { 315, "Parksville, British Columbia" },
                    { 316, "Cowansville, Quebec" },
                    { 317, "Becancour, Quebec" },
                    { 318, "Gravenhurst, Ontario" },
                    { 319, "Perth East, Ontario" },
                    { 320, "Prince Rupert, British Columbia" },
                    { 321, "Prevost, Quebec" },
                    { 322, "Sainte-Adele, Quebec" },
                    { 323, "Kentville, Nova Scotia" },
                    { 324, "Beauharnois, Quebec" },
                    { 325, "Les Iles-de-la-Madeleine, Quebec" },
                    { 326, "Wellington North, Ontario" },
                    { 327, "St. Andrews, Manitoba" },
                    { 328, "Carleton Place, Ontario" },
                    { 329, "Whistler, British Columbia" },
                    { 330, "Brighton, Ontario" },
                    { 331, "Tiny, Ontario" },
                    { 332, "Gander, Newfoundland and Labrador" },
                    { 333, "Sidney, British Columbia" },
                    { 334, "Rothesay, New Brunswick" },
                    { 335, "Brock, Ontario" },
                    { 336, "Summerland, British Columbia" },
                    { 337, "Val-des-Monts, Quebec" },
                    { 338, "Tache, Manitoba" },
                    { 339, "Montmagny, Quebec" },
                    { 340, "Erin, Ontario" },
                    { 341, "Kincardine, Ontario" },
                    { 342, "North Dundas, Ontario" },
                    { 343, "Wellesley, Ontario" },
                    { 344, "Estevan, Saskatchewan" },
                    { 345, "North Saanich, British Columbia" },
                    { 346, "Warman, Saskatchewan" },
                    { 347, "La Tuque, Quebec" },
                    { 348, "Norwich, Ontario" },
                    { 349, "Meaford, Ontario" },
                    { 350, "Adjala-Tosorontio, Ontario" },
                    { 351, "Hamilton Township, Ontario" },
                    { 352, "St. Clements, Manitoba" },
                    { 353, "Saint-Amable, Quebec" },
                    { 354, "Weyburn, Saskatchewan" },
                    { 355, "South Dundas, Ontario" },
                    { 356, "L'Ile-Perrot, Quebec" },
                    { 357, "Notre-Dame-de-l'Ile-Perrot, Quebec" },
                    { 358, "Williams Lake, British Columbia" },
                    { 359, "Elliot Lake, Ontario" },
                    { 360, "Cantley, Quebec" },
                    { 361, "Nelson, British Columbia" },
                    { 362, "Lambton Shores, Ontario" },
                    { 363, "Mapleton, Ontario" },
                    { 364, "Georgian Bluffs, Ontario" },
                    { 365, "Rawdon, Quebec" },
                    { 366, "Campbellton, New Brunswick" },
                    { 367, "View Royal, British Columbia" },
                    { 368, "Coldstream, British Columbia" },
                    { 369, "Chester, Nova Scotia" },
                    { 370, "Queens, Nova Scotia" },
                    { 371, "Selkirk, Manitoba" },
                    { 372, "Saint-Felicien, Quebec" },
                    { 373, "Hawkesbury, Ontario" },
                    { 374, "Roberval, Quebec" },
                    { 375, "Sainte-Agathe-des-Monts, Quebec" },
                    { 376, "North Dumfries, Ontario" },
                    { 377, "Rideau Lakes, Ontario" },
                    { 378, "Sechelt, British Columbia" },
                    { 379, "North Glengarry, Ontario" },
                    { 380, "South Huron, Ontario" },
                    { 381, "Marieville, Quebec" },
                    { 382, "Tay, Ontario" },
                    { 383, "Temiskaming Shores, Ontario" },
                    { 384, "Hinton, Alberta" },
                    { 385, "Saint-Sauveur, Quebec" },
                    { 386, "Quesnel, British Columbia" },
                    { 387, "Elizabethtown-Kitley, Ontario" },
                    { 388, "Morinville, Alberta" },
                    { 389, "Grey Highlands, Ontario" },
                    { 390, "Stratford, Prince Edward Island" },
                    { 391, "Alfred and Plantagenet, Ontario" },
                    { 392, "Mont-Tremblant, Quebec" },
                    { 393, "Martensville, Saskatchewan" },
                    { 394, "Saint-Raymond, Quebec" },
                    { 395, "Amherst, Nova Scotia" },
                    { 396, "Ramara, Ontario" },
                    { 397, "Bois-des-Filion, Quebec" },
                    { 398, "Leeds and the Thousand Islands, Ontario" },
                    { 399, "Carignan, Quebec" },
                    { 400, "Brockton, Ontario" },
                    { 401, "Laurentian Valley, Ontario" },
                    { 402, "East St. Paul, Manitoba" },
                    { 403, "Lorraine, Quebec" },
                    { 404, "Sainte-Julienne, Quebec" },
                    { 405, "Blackfalds, Alberta" },
                    { 406, "Malahide, Ontario" },
                    { 407, "Oromocto, New Brunswick" },
                    { 408, "Olds, Alberta" },
                    { 409, "Huron East, Ontario" },
                    { 410, "Stanley, Manitoba" },
                    { 411, "Penetanguishene, Ontario" },
                    { 412, "Qualicum Beach, British Columbia" },
                    { 413, "Notre-Dame-des-Prairies, Quebec" },
                    { 414, "West Perth, Ontario" },
                    { 415, "Cavan Monaghan, Ontario" },
                    { 416, "Arnprior, Ontario" },
                    { 417, "Smiths Falls, Ontario" },
                    { 418, "Pont-Rouge, Quebec" },
                    { 419, "Champlain, Ontario" },
                    { 420, "Coaticook, Quebec" },
                    { 421, "Minto, Ontario" },
                    { 422, "Morden, Manitoba" },
                    { 423, "Mono, Ontario" },
                    { 424, "Corman Park No. 344, Saskatchewan" },
                    { 425, "Ladysmith, British Columbia" },
                    { 426, "Bridgewater, Nova Scotia" },
                    { 427, "Dauphin, Manitoba" },
                    { 428, "Otterburn Park, Quebec" },
                    { 429, "Taber, Alberta" },
                    { 430, "South Bruce Peninsula, Ontario" },
                    { 431, "Edson, Alberta" },
                    { 432, "Farnham, Quebec" },
                    { 433, "Kapuskasing, Ontario" },
                    { 434, "La Malbaie, Quebec" },
                    { 435, "Renfrew, Ontario" },
                    { 436, "Coaldale, Alberta" },
                    { 437, "Portugal Cove-St. Philip's, Newfoundland and Labrador" },
                    { 438, "Zorra, Ontario" },
                    { 439, "Kitimat, British Columbia" },
                    { 440, "Shelburne, Ontario" },
                    { 441, "Happy Valley, Newfoundland and Labrador" },
                    { 442, "Saint-Hippolyte, Quebec" },
                    { 443, "Castlegar, British Columbia" },
                    { 444, "Church Point, Nova Scotia" },
                    { 445, "Drumheller, Alberta" },
                    { 446, "Kirkland Lake, Ontario" },
                    { 447, "Argyle, Nova Scotia" },
                    { 448, "Torbay, Newfoundland and Labrador" },
                    { 449, "La Peche, Quebec" },
                    { 450, "Banff, Alberta" },
                    { 451, "Innisfail, Alberta" },
                    { 452, "Nicolet, Quebec" },
                    { 453, "Rockwood, Manitoba" },
                    { 454, "Drummond/North Elmsley, Ontario" },
                    { 455, "Dryden, Ontario" },
                    { 456, "Iqaluit, Nunavut" },
                    { 457, "Fort Frances, Ontario" },
                    { 458, "La Sarre, Quebec" },
                    { 459, "Trail, British Columbia" },
                    { 460, "Chandler, Quebec" },
                    { 461, "Stone Mills, Ontario" },
                    { 462, "Hanover, Ontario" },
                    { 463, "South-West Oxford, Ontario" },
                    { 464, "Acton Vale, Quebec" },
                    { 465, "Bromont, Quebec" },
                    { 466, "Beckwith, Ontario" },
                    { 467, "Goderich, Ontario" },
                    { 468, "Plympton-Wyoming, Ontario" },
                    { 469, "Central Huron, Ontario" },
                    { 470, "Rigaud, Quebec" },
                    { 471, "Louiseville, Quebec" },
                    { 472, "Chibougamau, Quebec" },
                    { 473, "Aylmer, Ontario" },
                    { 474, "Delson, Quebec" },
                    { 475, "Kimberley, British Columbia" },
                    { 476, "Blandford-Blenheim, Ontario" },
                    { 477, "Bayham, Ontario" },
                    { 478, "Augusta, Ontario" },
                    { 479, "Puslinch, Ontario" },
                    { 480, "Beauport, Quebec" },
                    { 481, "Saint-Remi, Quebec" },
                    { 482, "St. Marys, Ontario" },
                    { 483, "Drayton Valley, Alberta" },
                    { 484, "Ponoka, Alberta" },
                    { 485, "Labrador City, Newfoundland and Labrador" },
                    { 486, "Donnacona, Quebec" },
                    { 487, "Southgate, Ontario" },
                    { 488, "McNab/Braeside, Ontario" },
                    { 489, "Macdonald, Manitoba" },
                    { 490, "Hampstead, Quebec" },
                    { 491, "Baie-Saint-Paul, Quebec" },
                    { 492, "Merritt, British Columbia" },
                    { 493, "Bluewater, Ontario" },
                    { 494, "East Zorra-Tavistock, Ontario" },
                    { 495, "Brownsburg, Quebec" },
                    { 496, "Stoneham-et-Tewkesbury, Quebec" },
                    { 497, "Asbestos, Quebec" },
                    { 498, "Huron-Kinloss, Ontario" },
                    { 499, "Coteau-du-Lac, Quebec" },
                    { 500, "The Blue Mountains, Ontario" },
                    { 501, "Whitewater Region, Ontario" },
                    { 502, "Edwardsburgh/Cardinal, Ontario" },
                    { 503, "Sainte-Anne-des-Monts, Quebec" },
                    { 504, "Old Chelsea, Quebec" },
                    { 505, "North Stormont, Ontario" },
                    { 506, "Alnwick/Haldimand, Ontario" },
                    { 507, "Peace River, Alberta" },
                    { 508, "Arran-Elderslie, Ontario" },
                    { 509, "Saint-Zotique, Quebec" },
                    { 510, "Val-Shefford, Quebec" },
                    { 511, "Douro-Dummer, Ontario" },
                    { 512, "Plessisville, Quebec" },
                    { 513, "Ritchot, Manitoba" },
                    { 514, "Otonabee-South Monaghan, Ontario" },
                    { 515, "Shediac, New Brunswick" },
                    { 516, "Slave Lake, Alberta" },
                    { 517, "Port-Cartier, Quebec" },
                    { 518, "Saint-Lambert-de-Lauzon, Quebec" },
                    { 519, "Barrington, Nova Scotia" },
                    { 520, "Rocky Mountain House, Alberta" },
                    { 521, "Chatsworth, Ontario" },
                    { 522, "Stephenville, Newfoundland and Labrador" },
                    { 523, "Muskoka Falls, Ontario" },
                    { 524, "Devon, Alberta" },
                    { 525, "Yarmouth, Nova Scotia" },
                    { 526, "Boischatel, Quebec" },
                    { 527, "Parry Sound, Ontario" },
                    { 528, "Pointe-Calumet, Quebec" },
                    { 529, "Beaubassin East / Beaubassin-est, New Brunswick" },
                    { 530, "Wainfleet, Ontario" },
                    { 531, "Cramahe, Ontario" },
                    { 532, "Beauceville, Quebec" },
                    { 533, "North Middlesex, Ontario" },
                    { 534, "Amqui, Quebec" },
                    { 535, "Sainte-Catherine-de-la-Jacques-Cartier, Quebec" },
                    { 536, "Clarenville, Newfoundland and Labrador" },
                    { 537, "Mont-Joli, Quebec" },
                    { 538, "Dysart et al, Ontario" },
                    { 539, "Wainwright, Alberta" },
                    { 540, "Contrecoeur, Quebec" },
                    { 541, "Beresford, New Brunswick" },
                    { 542, "Saint-Joseph-du-Lac, Quebec" },
                    { 543, "Hope, British Columbia" },
                    { 544, "Gimli, Manitoba" },
                    { 545, "Douglas, New Brunswick" },
                    { 546, "Saint-Apollinaire, Quebec" },
                    { 547, "Hindon Hill, Ontario" },
                    { 548, "Les Cedres, Quebec" },
                    { 549, "La Broquerie, Manitoba" },
                    { 550, "Kent, British Columbia" },
                    { 551, "Tweed, Ontario" },
                    { 552, "Saint-Felix-de-Valois, Quebec" },
                    { 553, "Bay Roberts, Newfoundland and Labrador" },
                    { 554, "Melfort, Saskatchewan" },
                    { 555, "Bonnyville, Alberta" },
                    { 556, "Stettler, Alberta" },
                    { 557, "Saint-Calixte, Quebec" },
                    { 558, "Lac-Megantic, Quebec" },
                    { 559, "Perth, Ontario" },
                    { 560, "Oliver Paipoonge, Ontario" },
                    { 561, "Humboldt, Saskatchewan" },
                    { 562, "Charlemagne, Quebec" },
                    { 563, "Pontiac, Quebec" },
                    { 564, "St. Paul, Alberta" },
                    { 565, "Petrolia, Ontario" },
                    { 566, "Southwest Middlesex, Ontario" },
                    { 567, "Front of Yonge, Ontario" },
                    { 568, "Vegreville, Alberta" },
                    { 569, "Sainte-Brigitte-de-Laval, Quebec" },
                    { 570, "Princeville, Quebec" },
                    { 571, "Vercheres, Quebec" },
                    { 572, "The Pas, Manitoba" },
                    { 573, "Saint-Cesaire, Quebec" },
                    { 574, "La Ronge, Saskatchewan" },
                    { 575, "Tay Valley, Ontario" },
                    { 576, "South Bruce, Ontario" },
                    { 577, "McMasterville, Quebec" },
                    { 578, "Redcliff, Alberta" },
                    { 579, "Crowsnest Pass, Alberta" },
                    { 580, "Saint-Philippe, Quebec" },
                    { 581, "Richelieu, Quebec" },
                    { 582, "Notre-Dame-du-Mont-Carmel, Quebec" },
                    { 583, "L'Ange-Gardien, Quebec" },
                    { 584, "Sainte-Martine, Quebec" },
                    { 585, "Saint-Pie, Quebec" },
                    { 586, "Peachland, British Columbia" },
                    { 587, "Ashfield-Colborne-Wawanosh, Ontario" },
                    { 588, "Trent Lakes, Ontario" },
                    { 589, "Northern Rockies, British Columbia" },
                    { 590, "Cookshire, Quebec" },
                    { 591, "West St. Paul, Manitoba" },
                    { 592, "Windsor, Quebec" },
                    { 593, "L'Epiphanie, Quebec" },
                    { 594, "Creston, British Columbia" },
                    { 595, "Smithers, British Columbia" },
                    { 596, "Cornwall, Prince Edward Island" },
                    { 597, "Meadow Lake, Saskatchewan" },
                    { 598, "Lanark Highlands, Ontario" },
                    { 599, "Sackville, New Brunswick" },
                    { 600, "Grand Falls, New Brunswick" },
                    { 601, "Cochrane, Ontario" },
                    { 602, "Marystown, Newfoundland and Labrador" },
                    { 603, "Sioux Lookout, Ontario" },
                    { 604, "Didsbury, Alberta" },
                    { 605, "Saint-Honore, Quebec" },
                    { 606, "Fernie, British Columbia" },
                    { 607, "Deer Lake, Newfoundland and Labrador" },
                    { 608, "Woodstock, New Brunswick" },
                    { 609, "Val-David, Quebec" },
                    { 610, "Flin Flon, Saskatchewan" },
                    { 611, "Hudson, Quebec" },
                    { 612, "Gananoque, Ontario" },
                    { 613, "Brokenhead, Manitoba" },
                    { 614, "Saint-Paul, Quebec" },
                    { 615, "Burton, New Brunswick" },
                    { 616, "Spallumcheen, British Columbia" },
                    { 617, "Westlock, Alberta" },
                    { 618, "Temiscouata-sur-le-Lac, Quebec" },
                    { 619, "Shannon, Quebec" },
                    { 620, "Osoyoos, British Columbia" },
                    { 621, "Montreal-Ouest, Quebec" },
                    { 622, "Hearst, Ontario" },
                    { 623, "Saint-Henri, Quebec" },
                    { 624, "Ste. Anne, Manitoba" },
                    { 625, "Antigonish, Nova Scotia" },
                    { 626, "Espanola, Ontario" },
                    { 627, "West Elgin, Ontario" },
                    { 628, "Flin Flon (Part), Manitoba" },
                    { 629, "Grand Bay-Westfield, New Brunswick" },
                    { 630, "Sainte-Anne-de-Bellevue, Quebec" },
                    { 631, "North Huron, Ontario" },
                    { 632, "Oliver, British Columbia" },
                    { 633, "Saint-Roch-de-l'Achigan, Quebec" },
                    { 634, "Stirling-Rawdon, Ontario" },
                    { 635, "Chisasibi, Quebec" },
                    { 636, "Carbonear, Newfoundland and Labrador" },
                    { 637, "Saint Marys, New Brunswick" },
                    { 638, "Chertsey, Quebec" },
                    { 639, "Armstrong, British Columbia" },
                    { 640, "Stonewall, Manitoba" },
                    { 641, "Shippagan, New Brunswick" },
                    { 642, "Lanoraie, Quebec" },
                    { 643, "Memramcook, New Brunswick" },
                    { 644, "Centre Hastings, Ontario" },
                    { 645, "Warwick, Quebec" },
                    { 646, "East Ferris, Ontario" },
                    { 647, "Hanwell, New Brunswick" },
                    { 648, "Saint-Joseph-de-Beauce, Quebec" },
                    { 649, "Metchosin, British Columbia" },
                    { 650, "Lucan Biddulph, Ontario" },
                    { 651, "Riviere-Rouge, Quebec" },
                    { 652, "Greenstone, Ontario" },
                    { 653, "Saint-Mathias-sur-Richelieu, Quebec" },
                    { 654, "Neepawa, Manitoba" },
                    { 655, "Gibsons, British Columbia" },
                    { 656, "Kindersley, Saskatchewan" },
                    { 657, "Jasper, Alberta" },
                    { 658, "Barrhead, Alberta" },
                    { 659, "Les Coteaux, Quebec" },
                    { 660, "Melville, Saskatchewan" },
                    { 661, "Saint-Germain-de-Grantham, Quebec" },
                    { 662, "Iroquois Falls, Ontario" },
                    { 663, "Havelock-Belmont-Methuen, Ontario" },
                    { 664, "Cornwallis, Manitoba" },
                    { 665, "Saint-Boniface, Quebec" },
                    { 666, "Edenwold No. 158, Saskatchewan" },
                    { 667, "Coverdale, New Brunswick" },
                    { 668, "Vanderhoof, British Columbia" },
                    { 669, "Southwold, Ontario" },
                    { 670, "Goulds, Newfoundland and Labrador" },
                    { 671, "Saint Stephen, New Brunswick" },
                    { 672, "Waterloo, Quebec" },
                    { 673, "Nipawin, Saskatchewan" },
                    { 674, "Neuville, Quebec" },
                    { 675, "Saint-Cyrille-de-Wendover, Quebec" },
                    { 676, "Central Frontenac, Ontario" },
                    { 677, "Mont-Orford, Quebec" },
                    { 678, "Saint-Jean-de-Matha, Quebec" },
                    { 679, "Seguin, Ontario" },
                    { 680, "Tyendinaga, Ontario" },
                    { 681, "Hampton, New Brunswick" },
                    { 682, "Sussex, New Brunswick" },
                    { 683, "Grand Forks, British Columbia" },
                    { 684, "La Pocatiere, Quebec" },
                    { 685, "Caraquet, New Brunswick" },
                    { 686, "Saint-Etienne-des-Gres, Quebec" },
                    { 687, "Altona, Manitoba" },
                    { 688, "Stellarton, Nova Scotia" },
                    { 689, "Wolfville, Nova Scotia" },
                    { 690, "New Maryland, New Brunswick" },
                    { 691, "Port Hardy, British Columbia" },
                    { 692, "Saint-Donat, Quebec" },
                    { 693, "Chateau-Richer, Quebec" },
                    { 694, "Madawaska Valley, Ontario" },
                    { 695, "Deep River, Ontario" },
                    { 696, "Asphodel-Norwood, Ontario" },
                    { 697, "Red Lake, Ontario" },
                    { 698, "Metabetchouan-Lac-a-la-Croix, Quebec" },
                    { 699, "Berthierville, Quebec" },
                    { 700, "Vermilion, Alberta" },
                    { 701, "Niverville, Manitoba" },
                    { 702, "Hastings Highlands, Ontario" },
                    { 703, "Carstairs, Alberta" },
                    { 704, "Danville, Quebec" },
                    { 705, "Channel-Port aux Basques, Newfoundland and Labrador" },
                    { 706, "Battleford, Saskatchewan" },
                    { 707, "Lac-Etchemin, Quebec" },
                    { 708, "Saint-Antonin, Quebec" },
                    { 709, "Saint-Jacques, Quebec" },
                    { 710, "Swan River, Manitoba" },
                    { 711, "Sutton, Quebec" },
                    { 712, "Northern Bruce Peninsula, Ontario" },
                    { 713, "L'Islet-sur-Mer, Quebec" },
                    { 714, "Carleton-sur-Mer, Quebec" },
                    { 715, "Oka, Quebec" },
                    { 716, "Prescott, Ontario" },
                    { 717, "Amaranth, Ontario" },
                    { 718, "Marmora and Lake, Ontario" },
                    { 719, "Maniwaki, Quebec" },
                    { 720, "Morin-Heights, Quebec" },
                    { 721, "Dundas, New Brunswick" },
                    { 722, "Napierville, Quebec" },
                    { 723, "Crabtree, Quebec" },
                    { 724, "Bancroft, Ontario" },
                    { 725, "Saint-Tite, Quebec" },
                    { 726, "Howick, Ontario" },
                    { 727, "Dutton/Dunwich, Ontario" },
                    { 728, "Callander, Ontario" },
                    { 729, "Simonds, New Brunswick" },
                    { 730, "Baie-d'Urfe, Quebec" },
                    { 731, "New Richmond, Quebec" },
                    { 732, "Perth South, Ontario" },
                    { 733, "Roxton Pond, Quebec" },
                    { 734, "Sparwood, British Columbia" },
                    { 735, "Claresholm, Alberta" },
                    { 736, "Breslau, Ontario" },
                    { 737, "Montague, Ontario" },
                    { 738, "Cumberland, British Columbia" },
                    { 739, "Beaupre, Quebec" },
                    { 740, "Saint-Andre-Avellin, Quebec" },
                    { 741, "Saint-Ambroise-de-Kildare, Quebec" },
                    { 742, "East Angus, Quebec" },
                    { 743, "Rossland, British Columbia" },
                    { 744, "Mackenzie, British Columbia" },
                    { 745, "Golden, British Columbia" },
                    { 746, "Raymond, Alberta" },
                    { 747, "Saint-Adolphe-d'Howard, Quebec" },
                    { 748, "Warwick, Ontario" },
                    { 749, "Bowen Island, British Columbia" },
                    { 750, "Bonnechere Valley, Ontario" },
                    { 751, "Windsor, Nova Scotia" },
                    { 752, "Pincher Creek, Alberta" },
                    { 753, "Alnwick, New Brunswick" },
                    { 754, "Westville, Nova Scotia" },
                    { 755, "Fruitvale, British Columbia" },
                    { 756, "Pasadena, Newfoundland and Labrador" },
                    { 757, "Saint-Prosper, Quebec" },
                    { 758, "Ormstown, Quebec" },
                    { 759, "Cardston, Alberta" },
                    { 760, "Westbank, British Columbia" },
                    { 761, "De Salaberry, Manitoba" },
                    { 762, "Headingley, Manitoba" },
                    { 763, "Grande Cache, Alberta" },
                    { 764, "Atholville, New Brunswick" },
                    { 765, "Saint-Agapit, Quebec" },
                    { 766, "Prince Albert No. 461, Saskatchewan" },
                    { 767, "Casselman, Ontario" },
                    { 768, "Saint-Ambroise, Quebec" },
                    { 769, "Hay River, Northwest Territories" },
                    { 770, "Mistissini, Quebec" },
                    { 771, "Studholm, New Brunswick" },
                    { 772, "Lumby, British Columbia" },
                    { 773, "Saint-Faustin--Lac-Carre, Quebec" },
                    { 774, "Morris-Turnberry, Ontario" },
                    { 775, "Placentia, Newfoundland and Labrador" },
                    { 776, "Saint-Pascal, Quebec" },
                    { 777, "Mulmur, Ontario" },
                    { 778, "Blind River, Ontario" },
                    { 779, "Dunham, Quebec" },
                    { 780, "Havre-Saint-Pierre, Quebec" },
                    { 781, "Saint-Anselme, Quebec" },
                    { 782, "Trois-Pistoles, Quebec" },
                    { 783, "Grande-Riviere, Quebec" },
                    { 784, "Powassan, Ontario" },
                    { 785, "Malartic, Quebec" },
                    { 786, "Bonavista, Newfoundland and Labrador" },
                    { 787, "Killarney - Turtle Mountain, Manitoba" },
                    { 788, "Woodlands, Manitoba" },
                    { 789, "Lewisporte, Newfoundland and Labrador" },
                    { 790, "Saint-Denis-de-Brompton, Quebec" },
                    { 791, "Invermere, British Columbia" },
                    { 792, "Salisbury, New Brunswick" },
                    { 793, "Bifrost-Riverton, Manitoba" },
                    { 794, "Buckland No. 491, Saskatchewan" },
                    { 795, "Cartier, Manitoba" },
                    { 796, "Sainte-Anne-des-Lacs, Quebec" },
                    { 797, "Highlands East, Ontario" },
                    { 798, "Alexander, Manitoba" },
                    { 799, "Sainte-Claire, Quebec" },
                    { 800, "Perce, Quebec" },
                    { 801, "Saint-Jean-Port-Joli, Quebec" },
                    { 802, "East Hawkesbury, Ontario" },
                    { 803, "Bright, New Brunswick" },
                    { 804, "Penhold, Alberta" },
                    { 805, "Saint-Andre-d'Argenteuil, Quebec" },
                    { 806, "Saint-Come--Liniere, Quebec" },
                    { 807, "Saint-Sulpice, Quebec" },
                    { 808, "Marathon, Ontario" },
                    { 809, "Forestville, Quebec" },
                    { 810, "Inuvik, Northwest Territories" },
                    { 811, "Richmond, Quebec" },
                    { 812, "Lake Cowichan, British Columbia" },
                    { 813, "Sables-Spanish Rivers, Ontario" },
                    { 814, "Hillsburg-Roblin-Shell River, Manitoba" },
                    { 815, "Port Hawkesbury, Nova Scotia" },
                    { 816, "Three Hills, Alberta" },
                    { 817, "Lorette, Manitoba" },
                    { 818, "Paspebiac, Quebec" },
                    { 819, "Saint-Thomas, Quebec" },
                    { 820, "Saint-Jean-Baptiste, Quebec" },
                    { 821, "Portneuf, Quebec" },
                    { 822, "Pictou, Nova Scotia" },
                    { 823, "Tisdale, Saskatchewan" },
                    { 824, "Lake of Bays, Ontario" },
                    { 825, "High Level, Alberta" },
                    { 826, "Gibbons, Alberta" },
                    { 827, "Bishops Falls, Newfoundland and Labrador" },
                    { 828, "WestLake-Gladstone, Manitoba" },
                    { 829, "Normandin, Quebec" },
                    { 830, "Saint-Alphonse-Rodriguez, Quebec" },
                    { 831, "Beausejour, Manitoba" },
                    { 832, "Dalhousie, New Brunswick" },
                    { 833, "Saint-Alphonse-de-Granby, Quebec" },
                    { 834, "Lac du Bonnet, Manitoba" },
                    { 835, "Clermont, Quebec" },
                    { 836, "Virden, Manitoba" },
                    { 837, "Compton, Quebec" },
                    { 838, "White City, Saskatchewan" },
                    { 839, "Ellison, British Columbia" },
                    { 840, "Mont-Saint-Gregoire, Quebec" },
                    { 841, "Wellington, New Brunswick" },
                    { 842, "Merrickville, Ontario" },
                    { 843, "Saint-Liboire, Quebec" },
                    { 844, "Degelis, Quebec" },
                    { 845, "Morris, Manitoba" },
                    { 846, "Saint-Alexis-des-Monts, Quebec" },
                    { 847, "Cap-Saint-Ignace, Quebec" },
                    { 848, "Saint-Anaclet-de-Lessard, Quebec" },
                    { 849, "Carman, Manitoba" },
                    { 850, "Athens, Ontario" },
                    { 851, "Melancthon, Ontario" },
                    { 852, "Cap Sante, Quebec" },
                    { 853, "Harbour Grace, Newfoundland and Labrador" },
                    { 854, "Houston, British Columbia" },
                    { 855, "Adelaide-Metcalfe, Ontario" },
                    { 856, "Crossfield, Alberta" },
                    { 857, "Springdale, Newfoundland and Labrador" },
                    { 858, "Fort Macleod, Alberta" },
                    { 859, "Athabasca, Alberta" },
                    { 860, "Enderby, British Columbia" },
                    { 861, "Saint-Ferreol-les-Neiges, Quebec" },
                    { 862, "Laurentian Hills, Ontario" },
                    { 863, "Grand Valley, Ontario" },
                    { 864, "Senneterre, Quebec" },
                    { 865, "Sainte-Marie-Madeleine, Quebec" },
                    { 866, "Admaston/Bromley, Ontario" },
                    { 867, "Saint-Gabriel-de-Valcartier, Quebec" },
                    { 868, "North Algona Wilberforce, Ontario" },
                    { 869, "Kingston, New Brunswick" },
                    { 870, "Wawa, Ontario" },
                    { 871, "Saint-Christophe-d'Arthabaska, Quebec" },
                    { 872, "Sainte-Melanie, Quebec" },
                    { 873, "Ascot Corner, Quebec" },
                    { 874, "Horton, Ontario" },
                    { 875, "Saint-Michel, Quebec" },
                    { 876, "Botwood, Newfoundland and Labrador" },
                    { 877, "Saint-Paul-d'Abbotsford, Quebec" },
                    { 878, "Saint-Marc-des-Carrieres, Quebec" },
                    { 879, "Stanstead, Quebec" },
                    { 880, "Sainte-Anne-de-Beaupre, Quebec" },
                    { 881, "Sainte-Luce, Quebec" },
                    { 882, "Saint-Gabriel, Quebec" },
                    { 883, "Rankin Inlet, Nunavut" },
                    { 884, "Vanscoy No. 345, Saskatchewan" },
                    { 885, "Cedar, British Columbia" },
                    { 886, "Princeton, British Columbia" },
                    { 887, "La Loche, Saskatchewan" },
                    { 888, "Kingsclear, New Brunswick" },
                    { 889, "Ferme-Neuve, Quebec" },
                    { 890, "Thurso, Quebec" },
                    { 891, "Adstock, Quebec" },
                    { 892, "Shuniah, Ontario" },
                    { 893, "Enniskillen, Ontario" },
                    { 894, "Yamachiche, Quebec" },
                    { 895, "Saint-Maurice, Quebec" },
                    { 896, "Bonaventure, Quebec" },
                    { 897, "Val-Morin, Quebec" },
                    { 898, "Pohenegamook, Quebec" },
                    { 899, "Wakefield, New Brunswick" },
                    { 900, "Stoke, Quebec" },
                    { 901, "Sainte-Marguerite-du-Lac-Masson, Quebec" },
                    { 902, "Saint-Prime, Quebec" },
                    { 903, "Kuujjuaq, Quebec" },
                    { 904, "Atikokan, Ontario" },
                    { 905, "Grenville-sur-la-Rouge, Quebec" },
                    { 906, "North Cypress-Langford, Manitoba" },
                    { 907, "Sainte-Anne-de-Sorel, Quebec" },
                    { 908, "Macamic, Quebec" },
                    { 909, "Sundre, Alberta" },
                    { 910, "Rougemont, Quebec" },
                    { 911, "Piedmont, Quebec" },
                    { 912, "Grimshaw, Alberta" },
                    { 913, "Lac-des-Ecorces, Quebec" },
                    { 914, "Northeastern Manitoulin and the Islands, Ontario" },
                    { 915, "Pelican Narrows, Saskatchewan" },
                    { 916, "McDougall, Ontario" },
                    { 917, "Black Diamond, Alberta" },
                    { 918, "Saint-Pamphile, Quebec" },
                    { 919, "Bedford, Quebec" },
                    { 920, "Weedon-Centre, Quebec" },
                    { 921, "Lacolle, Quebec" },
                    { 922, "Saint-Gabriel-de-Brandon, Quebec" },
                    { 923, "Errington, British Columbia" },
                    { 924, "Coalhurst, Alberta" },
                    { 925, "French River / Riviere des Francais, Ontario" },
                    { 926, "Arviat, Nunavut" },
                    { 927, "Saint-David-de-Falardeau, Quebec" },
                    { 928, "Markstay, Ontario" },
                    { 929, "Spaniards Bay, Newfoundland and Labrador" },
                    { 930, "Cocagne, New Brunswick" },
                    { 931, "Saint-Bruno, Quebec" },
                    { 932, "Chetwynd, British Columbia" },
                    { 933, "Laurier-Station, Quebec" },
                    { 934, "Saint-Anicet, Quebec" },
                    { 935, "Saint-Mathieu-de-Beloeil, Quebec" },
                    { 936, "Cap-Chat, Quebec" },
                    { 937, "Sexsmith, Alberta" },
                    { 938, "Notre-Dame-de-Lourdes, Quebec" },
                    { 939, "Ville-Marie, Quebec" },
                    { 940, "Saint-Isidore, Quebec" },
                    { 941, "Shippegan, New Brunswick" },
                    { 942, "East Garafraxa, Ontario" },
                    { 943, "Pemberton, British Columbia" },
                    { 944, "Unity, Saskatchewan" },
                    { 945, "Rimbey, Alberta" },
                    { 946, "High Prairie, Alberta" },
                    { 947, "Turner Valley, Alberta" },
                    { 948, "Hanna, Alberta" },
                    { 949, "Fort Smith, Northwest Territories" },
                    { 950, "Maria, Quebec" },
                    { 951, "Saint-Chrysostome, Quebec" },
                    { 952, "Greater Madawaska, Ontario" },
                    { 953, "Berwick, Nova Scotia" },
                    { 954, "Saint-Damase, Quebec" },
                    { 955, "Lincoln, New Brunswick" },
                    { 956, "Disraeli, Quebec" },
                    { 957, "Sainte-Victoire-de-Sorel, Quebec" },
                    { 958, "Meadow Lake No. 588, Saskatchewan" },
                    { 959, "Elkford, British Columbia" },
                    { 960, "Georgian Bay, Ontario" },
                    { 961, "Saint-Alexandre, Quebec" },
                    { 962, "Herbertville, Quebec" },
                    { 963, "Moosomin, Saskatchewan" },
                    { 964, "North Kawartha, Ontario" },
                    { 965, "Sainte-Thecle, Quebec" },
                    { 966, "Trenton, Nova Scotia" },
                    { 967, "Fermont, Quebec" },
                    { 968, "Esterhazy, Saskatchewan" },
                    { 969, "Wickham, Quebec" },
                    { 970, "La Presentation, Quebec" },
                    { 971, "Beaverlodge, Alberta" },
                    { 972, "Sainte-Catherine-de-Hatley, Quebec" },
                    { 973, "Saint-Basile, Quebec" },
                    { 974, "Saint-Raphael, Quebec" },
                    { 975, "Holyrood, Newfoundland and Labrador" },
                    { 976, "Gracefield, Quebec" },
                    { 977, "Saint-Martin, Quebec" },
                    { 978, "Causapscal, Quebec" },
                    { 979, "Brigham, Quebec" },
                    { 980, "Perry, Ontario" },
                    { 981, "Port-Daniel--Gascons, Quebec" },
                    { 982, "Rosetown, Saskatchewan" },
                    { 983, "Minnedosa, Manitoba" },
                    { 984, "Labelle, Quebec" },
                    { 985, "Huntingdon, Quebec" },
                    { 986, "Hebertville, Quebec" },
                    { 987, "Black River-Matheson, Ontario" },
                    { 988, "Saint-Michel-des-Saints, Quebec" },
                    { 989, "Dufferin, Manitoba" },
                    { 990, "Saint-Victor, Quebec" },
                    { 991, "Sicamous, British Columbia" },
                    { 992, "Cap Pele, New Brunswick" },
                    { 993, "Kelsey, Manitoba" },
                    { 994, "Hagarty and Richards, Hagarty and Richards" },
                    { 995, "Alvinston, Ontario" },
                    { 996, "Dundurn No. 314, Saskatchewan" },
                    { 997, "Saint-Ephrem-de-Beauce, Quebec" },
                    { 998, "Assiniboia, Saskatchewan" },
                    { 999, "Temiscaming, Quebec" },
                    { 1000, "Magrath, Alberta" }
                });

            migrationBuilder.InsertData(
                table: "Locations",
                columns: new[] { "LocationID", "Address" },
                values: new object[,]
                {
                    { 1001, "Sainte-Genevieve-de-Berthier, Quebec" },
                    { 1002, "Buctouche, New Brunswick" },
                    { 1003, "Grand Manan, New Brunswick" },
                    { 1004, "Sainte-Madeleine, Quebec" },
                    { 1005, "Boissevain, Manitoba" },
                    { 1006, "Scott, Quebec" },
                    { 1007, "Sainte-Croix, Quebec" },
                    { 1008, "Algonquin Highlands, Ontario" },
                    { 1009, "Valcourt, Quebec" },
                    { 1010, "Saint George, New Brunswick" },
                    { 1011, "Paquetville, New Brunswick" },
                    { 1012, "Saint-Dominique, Quebec" },
                    { 1013, "Clearwater, British Columbia" },
                    { 1014, "Addington Highlands, Ontario" },
                    { 1015, "Lillooet, British Columbia" },
                    { 1016, "Burin, Newfoundland and Labrador" },
                    { 1017, "Grand Bank, Newfoundland and Labrador" },
                    { 1018, "Lery, Quebec" },
                    { 1019, "Minto, New Brunswick" },
                    { 1020, "Rosthern No. 403, Saskatchewan" },
                    { 1021, "Chase, British Columbia" },
                    { 1022, "Mansfield-et-Pontefract, Quebec" },
                    { 1023, "Saint-Denis, Quebec" },
                    { 1024, "Outlook, Saskatchewan" },
                    { 1025, "Mitchell, Manitoba" },
                    { 1026, "Saint-Gedeon-de-Beauce, Quebec" },
                    { 1027, "Saint-Leonard-d'Aston, Quebec" },
                    { 1028, "Lunenburg, Nova Scotia" },
                    { 1029, "Northesk, New Brunswick" },
                    { 1030, "Albanel, Quebec" },
                    { 1031, "St. Anthony, Newfoundland and Labrador" },
                    { 1032, "Pessamit, Quebec" },
                    { 1033, "Maskinonge, Quebec" },
                    { 1034, "Saint-Charles-de-Bellechasse, Quebec" },
                    { 1035, "Fogo Island, Newfoundland and Labrador" },
                    { 1036, "East Broughton, Quebec" },
                    { 1037, "Lantz, Nova Scotia" },
                    { 1038, "Calmar, Alberta" },
                    { 1039, "Highlands, British Columbia" },
                    { 1040, "Saint-Polycarpe, Quebec" },
                    { 1041, "Logy Bay-Middle Cove-Outer Cove, Newfoundland and Labrador" },
                    { 1042, "Deschambault, Quebec" },
                    { 1043, "Canora, Saskatchewan" },
                    { 1044, "Upper Miramichi, New Brunswick" },
                    { 1045, "Anmore, British Columbia" },
                    { 1046, "Hardwicke, New Brunswick" },
                    { 1047, "Saint-Come, Quebec" },
                    { 1048, "Waskaganish, Quebec" },
                    { 1049, "Twillingate, Newfoundland and Labrador" },
                    { 1050, "Saint-Quentin, New Brunswick" },
                    { 1051, "Lebel-sur-Quevillon, Quebec" },
                    { 1052, "Pilot Butte, Saskatchewan" },
                    { 1053, "Nanton, Alberta" },
                    { 1054, "Pierreville, Quebec" },
                    { 1055, "New-Wes-Valley, Newfoundland and Labrador" },
                    { 1056, "Pennfield Ridge, New Brunswick" },
                    { 1057, "West Interlake, Manitoba" },
                    { 1058, "Biggar, Saskatchewan" },
                    { 1059, "Britannia No. 502, Saskatchewan" },
                    { 1060, "Kent, New Brunswick" },
                    { 1061, "Wabana, Newfoundland and Labrador" },
                    { 1062, "Saint-Gilles, Quebec" },
                    { 1063, "Wendake, Quebec" },
                    { 1064, "Saint-Bernard, Quebec" },
                    { 1065, "Sainte-Cecile-de-Milton, Quebec" },
                    { 1066, "Saint-Roch-de-Richelieu, Quebec" },
                    { 1067, "Saint-Nazaire, Quebec" },
                    { 1068, "Saint-Elzear, Quebec" },
                    { 1069, "Hinchinbrooke, Quebec" },
                    { 1070, "Saint-Francois-Xavier-de-Brompton, Quebec" },
                    { 1071, "Papineauville, Quebec" },
                    { 1072, "Prairie View, Manitoba" },
                    { 1073, "Cowichan Bay, British Columbia" },
                    { 1074, "Saint-Ignace-de-Loyola, Quebec" },
                    { 1075, "Central Manitoulin, Ontario" },
                    { 1076, "Maple Creek, Saskatchewan" },
                    { 1077, "Glovertown, Newfoundland and Labrador" },
                    { 1078, "Tofield, Alberta" },
                    { 1079, "Madoc, Ontario" },
                    { 1080, "Upton, Quebec" },
                    { 1081, "Sainte-Anne-de-Sabrevois, Quebec" },
                    { 1082, "Logan Lake, British Columbia" },
                    { 1083, "Sainte-Anne-de-la-Perade, Quebec" },
                    { 1084, "Saint-Damien-de-Buckland, Quebec" },
                    { 1085, "Baker Lake, Nunavut" },
                    { 1086, "Saltair, British Columbia" },
                    { 1087, "Pouch Cove, Newfoundland and Labrador" },
                    { 1088, "Saint-Ferdinand, Quebec" },
                    { 1089, "Port McNeill, British Columbia" },
                    { 1090, "Digby, Nova Scotia" },
                    { 1091, "Manouane, Quebec" },
                    { 1092, "Saint-Gervais, Quebec" },
                    { 1093, "Neebing, Ontario" },
                    { 1094, "Redwater, Alberta" },
                    { 1095, "Saint-Alexandre-de-Kamouraska, Quebec" },
                    { 1096, "Saint-Marc-sur-Richelieu, Quebec" },
                    { 1097, "Mandeville, Quebec" },
                    { 1098, "Caplan, Quebec" },
                    { 1099, "Point Edward, Ontario" },
                    { 1100, "Allardville, New Brunswick" },
                    { 1101, "Waterville, Quebec" },
                    { 1102, "Saint-Damien, Quebec" },
                    { 1103, "Lac-Nominingue, Quebec" },
                    { 1104, "Obedjiwan, Quebec" },
                    { 1105, "Rama, Saskatchewan" },
                    { 1106, "McCreary, Manitoba" },
                    { 1107, "Deloraine-Winchester, Manitoba" },
                    { 1108, "Oakland-Wawanesa, Manitoba" },
                    { 1109, "Brenda-Waskada, Manitoba" },
                    { 1110, "Russell-Binscarth, Manitoba" },
                    { 1111, "Ellice-Archie, Manitoba" },
                    { 1112, "Souris-Glenwood, Manitoba" },
                    { 1113, "Riverdale, Manitoba" },
                    { 1114, "Pembina, Manitoba" },
                    { 1115, "Wallace-Woodworth, Manitoba" },
                    { 1116, "Lorne, Manitoba" },
                    { 1117, "Ethelbert, Manitoba" },
                    { 1118, "Yellowhead, Manitoba" },
                    { 1119, "Swan Valley West, Manitoba" },
                    { 1120, "Grey, Manitoba" },
                    { 1121, "Gilbert Plains, Manitoba" },
                    { 1122, "Norfolk-Treherne, Manitoba" },
                    { 1123, "Hamiota, Manitoba" },
                    { 1124, "Emerson-Franklin, Manitoba" },
                    { 1125, "Sifton, Manitoba" },
                    { 1126, "Rossburn, Manitoba" },
                    { 1127, "Grand View, Manitoba" },
                    { 1128, "Grassland, Manitoba" },
                    { 1129, "Louise, Manitoba" },
                    { 1130, "Ste. Rose, Manitoba" },
                    { 1131, "Cartwright-Roblin, Manitoba" },
                    { 1132, "Mossey River, Manitoba" },
                    { 1133, "Lakeshore, Manitoba" },
                    { 1134, "Riding Mountain West, Manitoba" },
                    { 1135, "Clanwilliam-Erickson, Manitoba" },
                    { 1136, "Glenboro-South Cypress, Manitoba" },
                    { 1137, "North Norfolk, Manitoba" },
                    { 1138, "Reinland, Manitoba" },
                    { 1139, "Minitonas-Bowsman, Manitoba" },
                    { 1140, "Kippens, Newfoundland and Labrador" },
                    { 1141, "Blucher, Saskatchewan" },
                    { 1142, "Hatley, Quebec" },
                    { 1143, "Saint-Gedeon, Quebec" },
                    { 1144, "Kingsey Falls, Quebec" },
                    { 1145, "Provost, Alberta" },
                    { 1146, "Saint-Charles, New Brunswick" },
                    { 1147, "Mattawa, Ontario" },
                    { 1148, "Tumbler Ridge, British Columbia" },
                    { 1149, "Terrasse-Vaudreuil, Quebec" },
                    { 1150, "L'Ascension-de-Notre-Seigneur, Quebec" },
                    { 1151, "Bow Island, Alberta" },
                    { 1152, "Barraute, Quebec" },
                    { 1153, "One Hundred Mile House, British Columbia" },
                    { 1154, "Kedgwick, New Brunswick" },
                    { 1155, "Gambo, Newfoundland and Labrador" },
                    { 1156, "Saint-Liguori, Quebec" },
                    { 1157, "Bonfield, Ontario" },
                    { 1158, "Pointe-Lebel, Quebec" },
                    { 1159, "Saint Mary, New Brunswick" },
                    { 1160, "Saint-Patrice-de-Sherrington, Quebec" },
                    { 1161, "Fox Creek, Alberta" },
                    { 1162, "Dawn-Euphemia, Ontario" },
                    { 1163, "Chapleau, Ontario" },
                    { 1164, "Saint-Esprit, Quebec" },
                    { 1165, "Westfield Beach, New Brunswick" },
                    { 1166, "Montague, Prince Edward Island" },
                    { 1167, "Mashteuiatsh, Quebec" },
                    { 1168, "Saint-Francois-du-Lac, Quebec" },
                    { 1169, "Eel River Crossing, New Brunswick" },
                    { 1170, "Saint-Fulgence, Quebec" },
                    { 1171, "Millet, Alberta" },
                    { 1172, "Vallee-Jonction, Quebec" },
                    { 1173, "Saint-Georges-de-Cacouna, Quebec" },
                    { 1174, "Lumsden No. 189, Saskatchewan" },
                    { 1175, "Manitouwadge, Ontario" },
                    { 1176, "Wellington, Ontario" },
                    { 1177, "Swift Current No. 137, Saskatchewan" },
                    { 1178, "Tofino, British Columbia" },
                    { 1179, "Fort Qu'Appelle, Saskatchewan" },
                    { 1180, "Vulcan, Alberta" },
                    { 1181, "Indian Head, Saskatchewan" },
                    { 1182, "Petit Rocher, New Brunswick" },
                    { 1183, "Wabush, Newfoundland and Labrador" },
                    { 1184, "Saint-Fabien, Quebec" },
                    { 1185, "Watrous, Saskatchewan" },
                    { 1186, "North Frontenac, Ontario" },
                    { 1187, "Lac-Superieur, Quebec" },
                    { 1188, "Les Escoumins, Quebec" },
                    { 1189, "Richibucto, New Brunswick" },
                    { 1190, "Riviere-Beaudette, Quebec" },
                    { 1191, "Saint-Barthelemy, Quebec" },
                    { 1192, "Nisga'a, British Columbia" },
                    { 1193, "Austin, Quebec" },
                    { 1194, "Saint-Mathieu, Quebec" },
                    { 1195, "Saint-Paul-de-l'Ile-aux-Noix, Quebec" },
                    { 1196, "Orkney No. 244, Saskatchewan" },
                    { 1197, "Behchoko, Northwest Territories" },
                    { 1198, "Saint-Joseph-de-Coleraine, Quebec" },
                    { 1199, "Saint-Cyprien-de-Napierville, Quebec" },
                    { 1200, "Sayabec, Quebec" },
                    { 1201, "Valleyview, Alberta" },
                    { 1202, "Deleage, Quebec" },
                    { 1203, "Potton, Quebec" },
                    { 1204, "Sainte-Beatrix, Quebec" },
                    { 1205, "Sainte-Justine, Quebec" },
                    { 1206, "Eastman, Quebec" },
                    { 1207, "Saint-Valerien-de-Milton, Quebec" },
                    { 1208, "Saint-Cuthbert, Quebec" },
                    { 1209, "Saint-Blaise-sur-Richelieu, Quebec" },
                    { 1210, "Middleton, Nova Scotia" },
                    { 1211, "Maugerville, New Brunswick" },
                    { 1212, "Dalmeny, Saskatchewan" },
                    { 1213, "Kamsack, Saskatchewan" },
                    { 1214, "Lumsden, Saskatchewan" },
                    { 1215, "Trinity Bay North, Newfoundland and Labrador" },
                    { 1216, "Saint-Michel-de-Bellechasse, Quebec" },
                    { 1217, "Sainte-Angele-de-Monnoir, Quebec" },
                    { 1218, "Picture Butte, Alberta" },
                    { 1219, "Sacre-Coeur-Saguenay, Quebec" },
                    { 1220, "Saint-Louis, New Brunswick" },
                    { 1221, "Victoria, Newfoundland and Labrador" },
                    { 1222, "Saint-Robert, Quebec" },
                    { 1223, "Armstrong, Manitoba" },
                    { 1224, "Saint-Pierre-de-l'Ile-d'Orleans, Quebec" },
                    { 1225, "La Guadeloupe, Quebec" },
                    { 1226, "Saint Andrews, New Brunswick" },
                    { 1227, "Burns Lake, British Columbia" },
                    { 1228, "Povungnituk, Quebec" },
                    { 1229, "Manners Sutton, New Brunswick" },
                    { 1230, "Gore, Quebec" },
                    { 1231, "Deseronto, Ontario" },
                    { 1232, "Lamont, Alberta" },
                    { 1233, "Chambord, Quebec" },
                    { 1234, "Dudswell, Quebec" },
                    { 1235, "Wynyard, Saskatchewan" },
                    { 1236, "Cambridge Bay, Nunavut" },
                    { 1237, "Saint-Narcisse, Quebec" },
                    { 1238, "Frontenac Islands, Ontario" },
                    { 1239, "Waswanipi, Quebec" },
                    { 1240, "Inukjuak, Quebec" },
                    { 1241, "Piney, Manitoba" },
                    { 1242, "Komoka, Ontario" },
                    { 1243, "Saint-Zacharie, Quebec" },
                    { 1244, "Hemmingford, Quebec" },
                    { 1245, "Shelburne, Nova Scotia" },
                    { 1246, "Saint-Clet, Quebec" },
                    { 1247, "Carberry, Manitoba" },
                    { 1248, "Brighton, New Brunswick" },
                    { 1249, "Saint-Antoine, New Brunswick" },
                    { 1250, "Warfield, British Columbia" },
                    { 1251, "Northampton, New Brunswick" },
                    { 1252, "Saint-Ours, Quebec" },
                    { 1253, "Stephenville Crossing, Newfoundland and Labrador" },
                    { 1254, "Sainte-Anne-de-la-Pocatiere, Quebec" },
                    { 1255, "Ucluelet, British Columbia" },
                    { 1256, "Saint-Placide, Quebec" },
                    { 1257, "Barriere, British Columbia" },
                    { 1258, "Fisher, Manitoba" },
                    { 1259, "Nipissing, Ontario" },
                    { 1260, "Sainte-Clotilde, Quebec" },
                    { 1261, "Shaunavon, Saskatchewan" },
                    { 1262, "Wicklow, New Brunswick" },
                    { 1263, "Southesk, New Brunswick" },
                    { 1264, "Nouvelle, Quebec" },
                    { 1265, "Rosthern, Saskatchewan" },
                    { 1266, "Yamaska, Quebec" },
                    { 1267, "Neguac, New Brunswick" },
                    { 1268, "Flat Rock, Newfoundland and Labrador" },
                    { 1269, "Igloolik, Nunavut" },
                    { 1270, "Grunthal, Manitoba" },
                    { 1271, "Naramata, British Columbia" },
                    { 1272, "Saint-Elie-de-Caxton, Quebec" },
                    { 1273, "Blumenort, Manitoba" },
                    { 1274, "Balmoral, New Brunswick" },
                    { 1275, "Price, Quebec" },
                    { 1276, "Rosedale, Manitoba" },
                    { 1277, "Saint-Jacques-le-Mineur, Quebec" },
                    { 1278, "Huron Shores, Ontario" },
                    { 1279, "Champlain, Quebec" },
                    { 1280, "Whitehead, Manitoba" },
                    { 1281, "Saint-Antoine-sur-Richelieu, Quebec" },
                    { 1282, "Saint-Pacome, Quebec" },
                    { 1283, "Saint-Stanislas-de-Kostka, Quebec" },
                    { 1284, "Frontenac, Quebec" },
                    { 1285, "Stuartburn, Manitoba" },
                    { 1286, "Yamaska-Est, Quebec" },
                    { 1287, "Sainte-Emelie-de-l'Energie, Quebec" },
                    { 1288, "Saint-Charles-sur-Richelieu, Quebec" },
                    { 1289, "Saint-Joseph-de-Sorel, Quebec" },
                    { 1290, "Nipigon, Ontario" },
                    { 1291, "Riviere-Blanche, Quebec" },
                    { 1292, "Sainte-Helene-de-Bagot, Quebec" },
                    { 1293, "Franklin Centre, Quebec" },
                    { 1294, "Harbour Breton, Newfoundland and Labrador" },
                    { 1295, "Massey Drive, Newfoundland and Labrador" },
                    { 1296, "Mille-Isles, Quebec" },
                    { 1297, "Wilton No. 472, Saskatchewan" },
                    { 1298, "Lyster, Quebec" },
                    { 1299, "Oakview, Manitoba" },
                    { 1300, "Balgonie, Saskatchewan" },
                    { 1301, "Harrison Park, Manitoba" },
                    { 1302, "Kensington, Prince Edward Island" },
                    { 1303, "Witless Bay, Newfoundland and Labrador" },
                    { 1304, "Pond Inlet, Nunavut" },
                    { 1305, "Royston, British Columbia" },
                    { 1306, "Sainte-Clotilde-de-Horton, Quebec" },
                    { 1307, "Burford, Ontario" },
                    { 1308, "Fossambault-sur-le-Lac, Quebec" },
                    { 1309, "Saint-Benoit-Labre, Quebec" },
                    { 1310, "Coombs, British Columbia" },
                    { 1311, "Terrace Bay, Ontario" },
                    { 1312, "Chapais, Quebec" },
                    { 1313, "Saint-Honore-de-Shenley, Quebec" },
                    { 1314, "Cleveland, Quebec" },
                    { 1315, "Meredith and Aberdeen Additional, Meredith and Aberdeen Additional" },
                    { 1316, "Messines, Quebec" },
                    { 1317, "Saint-Jean-de-Dieu, Quebec" },
                    { 1318, "Nakusp, British Columbia" },
                    { 1319, "Florenceville, New Brunswick" },
                    { 1320, "Saint-Antoine-de-Tilly, Quebec" },
                    { 1321, "Lakeview, British Columbia" },
                    { 1322, "Humbermouth, Newfoundland and Labrador" },
                    { 1323, "Fort St. James, British Columbia" },
                    { 1324, "Saint-Francois-de-la-Riviere-du-Sud, Quebec" },
                    { 1325, "Saint-Jacques, New Brunswick" },
                    { 1326, "Uashat, Quebec" },
                    { 1327, "Perth, New Brunswick" },
                    { 1328, "Eeyou Istchee Baie-James, Quebec" },
                    { 1329, "Shellbrook No. 493, Saskatchewan" },
                    { 1330, "Shawville, Quebec" },
                    { 1331, "Saint-Lucien, Quebec" },
                    { 1332, "Lambton, Quebec" },
                    { 1333, "Saint-Laurent-de-l'Ile-d'Orleans, Quebec" },
                    { 1334, "Saint-Flavien, Quebec" },
                    { 1335, "Grenville, Quebec" },
                    { 1336, "Chute-aux-Outardes, Quebec" },
                    { 1337, "Sainte-Marcelline-de-Kildare, Quebec" },
                    { 1338, "Saint-Felix-de-Kingsey, Quebec" },
                    { 1339, "Upper Island Cove, Newfoundland and Labrador" },
                    { 1340, "Glenelg, New Brunswick" },
                    { 1341, "Sainte-Elisabeth, Quebec" },
                    { 1342, "Ashcroft, British Columbia" },
                    { 1343, "Clarkes Beach, Newfoundland and Labrador" },
                    { 1344, "Saint-Bernard-de-Lacolle, Quebec" },
                    { 1345, "Belledune, New Brunswick" },
                    { 1346, "Saint-Guillaume, Quebec" },
                    { 1347, "Venise-en-Quebec, Quebec" },
                    { 1348, "Maliotenam, Quebec" },
                    { 1349, "Ripon, Quebec" },
                    { 1350, "Hilliers, British Columbia" },
                    { 1351, "Saint-Joseph, New Brunswick" },
                    { 1352, "Saint-Paulin, Quebec" },
                    { 1353, "Bon Accord, Alberta" },
                    { 1354, "Saint David, New Brunswick" },
                    { 1355, "Saint-Albert, Quebec" },
                    { 1356, "Matagami, Quebec" },
                    { 1357, "Springfield, New Brunswick" },
                    { 1358, "Amherst, Quebec" },
                    { 1359, "Notre-Dame-du-Laus, Quebec" },
                    { 1360, "St. George, New Brunswick" },
                    { 1361, "Wembley, Alberta" },
                    { 1362, "Victoria, Manitoba" },
                    { 1363, "Springbrook, Alberta" },
                    { 1364, "Saint-Tite-des-Caps, Quebec" },
                    { 1365, "Hudson Bay, Saskatchewan" },
                    { 1366, "Pinawa, Manitoba" },
                    { 1367, "Lyndoch and Raglan, Lyndoch and Raglan" },
                    { 1368, "Carlyle, Saskatchewan" },
                    { 1369, "Keremeos, British Columbia" },
                    { 1370, "Val-Joli, Quebec" },
                    { 1371, "Gold River, British Columbia" },
                    { 1372, "Saint-Casimir, Quebec" },
                    { 1373, "Bay Bulls, Newfoundland and Labrador" },
                    { 1374, "Langham, Saskatchewan" },
                    { 1375, "Frenchman Butte, Saskatchewan" },
                    { 1376, "Gordon, New Brunswick" },
                    { 1377, "Kugluktuk, Nunavut" },
                    { 1378, "Saint-Malachie, Quebec" },
                    { 1379, "Southampton, New Brunswick" },
                    { 1380, "Salluit, Quebec" },
                    { 1381, "Pangnirtung, Nunavut" },
                    { 1382, "Saint-Louis-de-Gonzague, Quebec" },
                    { 1383, "Moosonee, Ontario" },
                    { 1384, "Englehart, Ontario" },
                    { 1385, "Saint-Urbain, Quebec" },
                    { 1386, "Tring-Jonction, Quebec" },
                    { 1387, "Nauwigewauk, New Brunswick" },
                    { 1388, "Pointe-a-la-Croix, Quebec" },
                    { 1389, "Denmark, New Brunswick" },
                    { 1390, "Saint-Joachim, Quebec" },
                    { 1391, "Torch River No. 488, Saskatchewan" },
                    { 1392, "Saint-Theodore-d'Acton, Quebec" },
                    { 1393, "Grindrod, British Columbia" },
                    { 1394, "L' Isle-Verte, Quebec" },
                    { 1395, "Harrison Hot Springs, British Columbia" },
                    { 1396, "Palmarolle, Quebec" },
                    { 1397, "Henryville, Quebec" },
                    { 1398, "Sussex Corner, New Brunswick" },
                    { 1399, "Saint-Odilon-de-Cranbourne, Quebec" },
                    { 1400, "Pipestone, Manitoba" },
                    { 1401, "Laurierville, Quebec" },
                    { 1402, "La Dore, Quebec" },
                    { 1403, "Lac-au-Saumon, Quebec" },
                    { 1404, "Wotton, Quebec" },
                    { 1405, "Prairie Lakes, Manitoba" },
                    { 1406, "Elk Point, Alberta" },
                    { 1407, "Shellbrook, Saskatchewan" },
                    { 1408, "Wemindji, Quebec" },
                    { 1409, "Cape Dorset, Nunavut" },
                    { 1410, "Strong, Ontario" },
                    { 1411, "Lappe, Ontario" },
                    { 1412, "Riviere-Heva, Quebec" },
                    { 1413, "Fort-Coulonge, Quebec" },
                    { 1414, "Irishtown-Summerside, Newfoundland and Labrador" },
                    { 1415, "Godmanchester, Quebec" },
                    { 1416, "Macklin, Saskatchewan" },
                    { 1417, "Armour, Ontario" },
                    { 1418, "Saint-Simon, Quebec" },
                    { 1419, "St. Francois Xavier, Manitoba" },
                    { 1420, "Tingwick, Quebec" },
                    { 1421, "Saint-Aubert, Quebec" },
                    { 1422, "Saint-Mathieu-du-Parc, Quebec" },
                    { 1423, "Wabasca, Alberta" },
                    { 1424, "Ragueneau, Quebec" },
                    { 1425, "Notre-Dame-du-Bon-Conseil, Quebec" },
                    { 1426, "Wasagamack, Manitoba" },
                    { 1427, "Saint-Ubalde, Quebec" },
                    { 1428, "Creighton, Saskatchewan" },
                    { 1429, "Fortune, Newfoundland and Labrador" },
                    { 1430, "Faraday, Ontario" },
                    { 1431, "Berthier-sur-Mer, Quebec" },
                    { 1432, "Frampton, Quebec" },
                    { 1433, "Magnetawan, Ontario" },
                    { 1434, "New Carlisle, Quebec" },
                    { 1435, "Laird No. 404, Saskatchewan" },
                    { 1436, "Petitcodiac, New Brunswick" },
                    { 1437, "Popkum, British Columbia" },
                    { 1438, "Norton, New Brunswick" },
                    { 1439, "Canwood No. 494, Saskatchewan" },
                    { 1440, "Wentworth-Nord, Quebec" },
                    { 1441, "Bas Caraquet, New Brunswick" },
                    { 1442, "Sainte-Ursule, Quebec" },
                    { 1443, "Dawson, Yukon" },
                    { 1444, "Nantes, Quebec" },
                    { 1445, "Lac-aux-Sables, Quebec" },
                    { 1446, "Stewiacke, Nova Scotia" },
                    { 1447, "Taylor, British Columbia" },
                    { 1448, "Rosser, Manitoba" },
                    { 1449, "Estevan No. 5, Saskatchewan" },
                    { 1450, "Falmouth, Nova Scotia" },
                    { 1451, "Vaudreuil-sur-le-Lac, Quebec" },
                    { 1452, "Grahamdale, Manitoba" },
                    { 1453, "Cardwell, New Brunswick" },
                    { 1454, "Two Hills, Alberta" },
                    { 1455, "Spiritwood No. 496, Saskatchewan" },
                    { 1456, "Legal, Alberta" },
                    { 1457, "Amulet, Quebec" },
                    { 1458, "Herouxville, Quebec" },
                    { 1459, "Pointe-des-Cascades, Quebec" },
                    { 1460, "Weldford, New Brunswick" },
                    { 1461, "Reynolds, Manitoba" },
                    { 1462, "St. Laurent, Manitoba" },
                    { 1463, "Lions Bay, British Columbia" },
                    { 1464, "L'Isle-aux-Allumettes, Quebec" },
                    { 1465, "Emo, Ontario" },
                    { 1466, "Sainte-Brigide-d'Iberville, Quebec" },
                    { 1467, "Les Eboulements, Quebec" },
                    { 1468, "Dunsmuir, British Columbia" },
                    { 1469, "Pointe-aux-Outardes, Quebec" },
                    { 1470, "Smooth Rock Falls, Ontario" },
                    { 1471, "Oxbow, Saskatchewan" },
                    { 1472, "Telkwa, British Columbia" },
                    { 1473, "Gjoa Haven, Nunavut" },
                    { 1474, "Sainte-Barbe, Quebec" },
                    { 1475, "Mayerthorpe, Alberta" },
                    { 1476, "Saint-Louis-du-Ha! Ha!, Quebec" },
                    { 1477, "Powerview-Pine Falls, Manitoba" },
                    { 1478, "Baie Verte, Newfoundland and Labrador" },
                    { 1479, "Saint-Edouard, Quebec" },
                    { 1480, "Charlo, New Brunswick" },
                    { 1481, "Hillsborough, New Brunswick" },
                    { 1482, "Bruederheim, Alberta" },
                    { 1483, "Burgeo, Newfoundland and Labrador" },
                    { 1484, "Wadena, Saskatchewan" },
                    { 1485, "Richmond, New Brunswick" },
                    { 1486, "Swan Hills, Alberta" },
                    { 1487, "Wilkie, Saskatchewan" },
                    { 1488, "Saint-Leonard, New Brunswick" },
                    { 1489, "Riviere-Bleue, Quebec" },
                    { 1490, "Noyan, Quebec" },
                    { 1491, "Ile-a-la-Crosse, Saskatchewan" },
                    { 1492, "Landmark, Manitoba" },
                    { 1493, "Saint-Hugues, Quebec" },
                    { 1494, "Chisholm, Ontario" },
                    { 1495, "Sainte-Anne-du-Sault, Quebec" },
                    { 1496, "La Conception, Quebec" },
                    { 1497, "Saint-Valere, Quebec" },
                    { 1498, "Sorrento, British Columbia" },
                    { 1499, "Lameque, New Brunswick" },
                    { 1500, "Thessalon, Ontario" },
                    { 1501, "L'Isle-aux-Coudres, Quebec" },
                    { 1502, "Nobleford, Alberta" },
                    { 1503, "Larouche, Quebec" },
                    { 1504, "South Qu'Appelle No. 157, Saskatchewan" },
                    { 1505, "Elton, Manitoba" },
                    { 1506, "Lorrainville, Quebec" },
                    { 1507, "Conestogo, Ontario" },
                    { 1508, "Upham, New Brunswick" },
                    { 1509, "St.-Charles, Ontario" },
                    { 1510, "Sainte-Lucie-des-Laurentides, Quebec" },
                    { 1511, "Saint-Alexis, Quebec" },
                    { 1512, "Gillam, Manitoba" },
                    { 1513, "Roxton Falls, Quebec" },
                    { 1514, "Montcalm, Manitoba" },
                    { 1515, "Clarendon, Quebec" },
                    { 1516, "Mervin No. 499, Saskatchewan" },
                    { 1517, "Saint-Ludger, Quebec" },
                    { 1518, "Coldwell, Manitoba" },
                    { 1519, "Saint-Arsene, Quebec" },
                    { 1520, "Racine, Quebec" },
                    { 1521, "Saint-Majorique-de-Grantham, Quebec" },
                    { 1522, "Saint-Zenon, Quebec" },
                    { 1523, "Saint-Armand, Quebec" },
                    { 1524, "Saint-Edouard-de-Lotbiniere, Quebec" },
                    { 1525, "Alonsa, Manitoba" },
                    { 1526, "Listuguj, Quebec" },
                    { 1527, "Bowden, Alberta" },
                    { 1528, "St. Joseph, Ontario" },
                    { 1529, "Osler, Saskatchewan" },
                    { 1530, "Saint-Hubert-de-Riviere-du-Loup, Quebec" },
                    { 1531, "Saint-Jude, Quebec" },
                    { 1532, "Dildo, Newfoundland and Labrador" },
                    { 1533, "La Minerve, Quebec" },
                    { 1534, "Lanigan, Saskatchewan" },
                    { 1535, "Lajord No. 128, Saskatchewan" },
                    { 1536, "Moonbeam, Ontario" },
                    { 1537, "Notre-Dame-des-Pins, Quebec" },
                    { 1538, "Saint-Alban, Quebec" },
                    { 1539, "Saint-Pierre-les-Becquets, Quebec" },
                    { 1540, "Arborg, Manitoba" },
                    { 1541, "Vauxhall, Alberta" },
                    { 1542, "Bayfield, Ontario" },
                    { 1543, "Beaver River, Saskatchewan" },
                    { 1544, "Irricana, Alberta" },
                    { 1545, "Labrecque, Quebec" },
                    { 1546, "New Bandon, New Brunswick" },
                    { 1547, "Wemotaci, Quebec" },
                    { 1548, "Sainte-Henedine, Quebec" },
                    { 1549, "L'Anse-Saint-Jean, Quebec" },
                    { 1550, "Bassano, Alberta" },
                    { 1551, "Parrsboro, Nova Scotia" },
                    { 1552, "Kaleden, British Columbia" },
                    { 1553, "St. George's, Newfoundland and Labrador" },
                    { 1554, "Fort Simpson, Northwest Territories" },
                    { 1555, "Akwesasne, Quebec" },
                    { 1556, "L'Avenir, Quebec" },
                    { 1557, "Ignace, Ontario" },
                    { 1558, "Claremont, Ontario" },
                    { 1559, "Teulon, Manitoba" },
                    { 1560, "Peel, New Brunswick" },
                    { 1561, "Musquash, New Brunswick" },
                    { 1562, "Notre-Dame-du-Portage, Quebec" },
                    { 1563, "St. Lawrence, Newfoundland and Labrador" },
                    { 1564, "Oxford, Nova Scotia" },
                    { 1565, "Minto-Odanah, Manitoba" },
                    { 1566, "St. Alban's, Newfoundland and Labrador" },
                    { 1567, "Saint James, New Brunswick" },
                    { 1568, "Saint-Norbert-d'Arthabaska, Quebec" },
                    { 1569, "Manning, Alberta" },
                    { 1570, "Glenella-Lansdowne, Manitoba" },
                    { 1571, "Saint-Hilarion, Quebec" },
                    { 1572, "Saint-Simeon, Quebec" },
                    { 1573, "Saint-Barnabe, Quebec" },
                    { 1574, "Sainte-Felicite, Quebec" },
                    { 1575, "Two Borders, Manitoba" },
                    { 1576, "Queensbury, New Brunswick" },
                    { 1577, "Bury, Quebec" },
                    { 1578, "Lac-Bouchette, Quebec" },
                    { 1579, "Saint-Lazare-de-Bellechasse, Quebec" },
                    { 1580, "Saint-Michel-du-Squatec, Quebec" },
                    { 1581, "Saint-Joachim-de-Shefford, Quebec" },
                    { 1582, "St-Pierre-Jolys, Manitoba" },
                    { 1583, "Grand-Remous, Quebec" },
                    { 1584, "Saint-Gabriel-de-Rimouski, Quebec" },
                    { 1585, "Armstrong, Ontario" },
                    { 1586, "Rogersville, New Brunswick" },
                    { 1587, "Langenburg, Saskatchewan" },
                    { 1588, "Sainte-Marie-Salome, Quebec" },
                    { 1589, "Moose Jaw No. 161, Saskatchewan" },
                    { 1590, "Saint-Cyprien, Quebec" },
                    { 1591, "Maidstone, Saskatchewan" },
                    { 1592, "Tres-Saint-Sacrement, Quebec" },
                    { 1593, "Battle River No. 438, Saskatchewan" },
                    { 1594, "Miltonvale Park, Prince Edward Island" },
                    { 1595, "McAdam, New Brunswick" },
                    { 1596, "Saints-Anges, Quebec" },
                    { 1597, "Saint-Urbain-Premier, Quebec" },
                    { 1598, "Centreville-Wareham-Trinity, Newfoundland and Labrador" },
                    { 1599, "Alberton, Prince Edward Island" },
                    { 1600, "Winnipeg Beach, Manitoba" },
                    { 1601, "Sainte-Agathe-de-Lotbiniere, Quebec" },
                    { 1602, "Salmo, British Columbia" },
                    { 1603, "Kipling, Saskatchewan" },
                    { 1604, "Sagamok, Ontario" },
                    { 1605, "Trecesson, Quebec" },
                    { 1606, "Tara, Ontario" },
                    { 1607, "Grande-Vallee, Quebec" },
                    { 1608, "Bertrand, New Brunswick" },
                    { 1609, "Newcastle, New Brunswick" },
                    { 1610, "Mont-Carmel, Quebec" },
                    { 1611, "Saint Martins, New Brunswick" },
                    { 1612, "Saint-Eugene, Quebec" },
                    { 1613, "Notre-Dame-des-Neiges, Quebec" },
                    { 1614, "Saint-Andre, New Brunswick" },
                    { 1615, "Centreville, Nova Scotia" },
                    { 1616, "Roland, Manitoba" },
                    { 1617, "Saint-Leon-de-Standon, Quebec" },
                    { 1618, "Saint-Modeste, Quebec" },
                    { 1619, "Carnduff, Saskatchewan" },
                    { 1620, "Carling, Ontario" },
                    { 1621, "Eckville, Alberta" },
                    { 1622, "Nain, Newfoundland and Labrador" },
                    { 1623, "Hillsburgh, Ontario" },
                    { 1624, "Foam Lake, Saskatchewan" },
                    { 1625, "Sainte-Sabine, Quebec" },
                    { 1626, "Saint-Maxime-du-Mont-Louis, Quebec" },
                    { 1627, "Blanc-Sablon, Quebec" },
                    { 1628, "Cobalt, Ontario" },
                    { 1629, "Gravelbourg, Saskatchewan" },
                    { 1630, "South River, Ontario" },
                    { 1631, "Hudson Bay No. 394, Saskatchewan" },
                    { 1632, "McKellar, Ontario" },
                    { 1633, "Frelighsburg, Quebec" },
                    { 1634, "Buffalo Narrows, Saskatchewan" },
                    { 1635, "Ayer's Cliff, Quebec" },
                    { 1636, "Les Mechins, Quebec" },
                    { 1637, "Sainte-Marguerite, Quebec" },
                    { 1638, "Saint-Claude, Quebec" },
                    { 1639, "Air Ronge, Saskatchewan" },
                    { 1640, "Chipman, New Brunswick" },
                    { 1641, "Girardville, Quebec" },
                    { 1642, "Saint-Bruno-de-Guigues, Quebec" },
                    { 1643, "Grenfell, Saskatchewan" },
                    { 1644, "Dorchester, New Brunswick" },
                    { 1645, "South Algonquin, Ontario" },
                    { 1646, "Windermere, British Columbia" },
                    { 1647, "Saint-Narcisse-de-Beaurivage, Quebec" },
                    { 1648, "Saint-Rene-de-Matane, Quebec" },
                    { 1649, "Sainte-Jeanne-d'Arc, Quebec" },
                    { 1650, "Plaisance, Quebec" },
                    { 1651, "Roxton-Sud, Quebec" },
                    { 1652, "St. Louis No. 431, Saskatchewan" },
                    { 1653, "Youbou, British Columbia" },
                    { 1654, "Duchess, Alberta" },
                    { 1655, "Saint-Frederic, Quebec" },
                    { 1656, "Viking, Alberta" },
                    { 1657, "Sioux Narrows-Nestor Falls, Ontario" },
                    { 1658, "Whitecourt, Alberta" },
                    { 1659, "Repulse Bay, Nunavut" },
                    { 1660, "Montreal-Est, Quebec" },
                    { 1661, "King, Ontario" },
                    { 1662, "Regina Beach, Saskatchewan" },
                    { 1663, "Saint-Patrice-de-Beaurivage, Quebec" },
                    { 1664, "Ootischenia, British Columbia" },
                    { 1665, "Hensall, Ontario" },
                    { 1666, "Bentley, Alberta" },
                    { 1667, "Durham, New Brunswick" },
                    { 1668, "Sainte-Marthe, Quebec" },
                    { 1669, "Notre-Dame-du-Nord, Quebec" },
                    { 1670, "Pinehouse, Saskatchewan" },
                    { 1671, "Saint-Aime-des-Lacs, Quebec" },
                    { 1672, "Lac-Drolet, Quebec" },
                    { 1673, "Preeceville, Saskatchewan" },
                    { 1674, "Maple Creek No. 111, Saskatchewan" },
                    { 1675, "Harbour Main-Chapel's Cove-Lakeview, Newfoundland and Labrador" },
                    { 1676, "Saint-Wenceslas, Quebec" },
                    { 1677, "Weyburn No. 67, Saskatchewan" },
                    { 1678, "Birch Hills, Saskatchewan" },
                    { 1679, "Wedgeport, Nova Scotia" },
                    { 1680, "Kerrobert, Saskatchewan" },
                    { 1681, "Havelock, New Brunswick" },
                    { 1682, "Eston, Saskatchewan" },
                    { 1683, "Sainte-Genevieve-de-Batiscan, Quebec" },
                    { 1684, "Saint-Justin, Quebec" },
                    { 1685, "Saint-Norbert, Quebec" },
                    { 1686, "Schreiber, Ontario" },
                    { 1687, "Trochu, Alberta" },
                    { 1688, "Botsford, New Brunswick" },
                    { 1689, "Riviere-Ouelle, Quebec" },
                    { 1690, "Greenwich, New Brunswick" },
                    { 1691, "Stukely-Sud, Quebec" },
                    { 1692, "Saint-Georges-de-Clarenceville, Quebec" },
                    { 1693, "Sainte-Therese-de-Gaspe, Quebec" },
                    { 1694, "Beachburg, Ontario" },
                    { 1695, "Desbiens, Quebec" },
                    { 1696, "Clyde River, Nunavut" },
                    { 1697, "La Macaza, Quebec" },
                    { 1698, "Souris, Prince Edward Island" },
                    { 1699, "Kindersley No. 290, Saskatchewan" },
                    { 1700, "Laird, Ontario" },
                    { 1701, "Falher, Alberta" },
                    { 1702, "Saint-Vallier, Quebec" },
                    { 1703, "Coleraine, Quebec" },
                    { 1704, "Melita, Manitoba" },
                    { 1705, "Noonan, New Brunswick" },
                    { 1706, "Sainte-Petronille, Quebec" },
                    { 1707, "Delisle, Saskatchewan" },
                    { 1708, "Bristol, Quebec" },
                    { 1709, "Mahone Bay, Nova Scotia" },
                    { 1710, "Waldheim, Saskatchewan" },
                    { 1711, "Saint-Sylvestre, Quebec" },
                    { 1712, "Taloyoak, Nunavut" },
                    { 1713, "Onoway, Alberta" },
                    { 1714, "Saint-Stanislas, Quebec" },
                    { 1715, "Malpeque, Prince Edward Island" },
                    { 1716, "Plantagenet, Ontario" },
                    { 1717, "Longue-Rive, Quebec" },
                    { 1718, "Argyle, Manitoba" },
                    { 1719, "Davidson, Saskatchewan" },
                    { 1720, "Plaster Rock, New Brunswick" },
                    { 1721, "Wilmot, New Brunswick" },
                    { 1722, "Valemount, British Columbia" },
                    { 1723, "Saint-Leonard-de-Portneuf, Quebec" },
                    { 1724, "Alberta Beach, Alberta" },
                    { 1725, "Saint-Narcisse-de-Rimouski, Quebec" },
                    { 1726, "Saint-Bonaventure, Quebec" },
                    { 1727, "Longlaketon No. 219, Saskatchewan" },
                    { 1728, "Papineau-Cameron, Ontario" },
                    { 1729, "Assiginack, Ontario" },
                    { 1730, "Brebeuf, Quebec" },
                    { 1731, "Hudson Hope, British Columbia" },
                    { 1732, "Prince, Ontario" },
                    { 1733, "Baie-du-Febvre, Quebec" },
                    { 1734, "Durham-Sud, Quebec" },
                    { 1735, "Melbourne, Quebec" },
                    { 1736, "Nipawin No. 487, Saskatchewan" },
                    { 1737, "Duck Lake No. 463, Saskatchewan" },
                    { 1738, "Oyen, Alberta" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Locations");
        }
    }
}
