/**
 * Buddies.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoResponse } from './userInfoResponse';

export interface ProjectProfileResponse {
  title: string;
  description: string;
  location: string;
  username: string;
  email: string;
  category: string;
  maxMembers: number;
  invitedUsers: Array<UserInfoResponse>;
  members: Array<UserInfoResponse>;
  membersYetToRate: Array<UserInfoResponse>;
  isFinished: boolean;
}
